### ISSUE TITLE
How to distinguish which package is a process in?

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Archive/auch#3]
We can know which package the process depends on from AUCH_ENV, shouldn't we make another environment to show which package is this process in?
e.g. pidXXX -> env -> AUCH_PKG=vim-nox[version] ?

**Comment by m13253** [comment]
I did not find any reason why this is necessary

**Comment by bobcao3** [comment]
`When some program attempts to write to /usr, the changes will have effects on the real files at /var/lib/auch/packages/<package name>. If it is a new file, the new file will be created at /var/lib/auch/custom/.`

Virtroofs need to know this.
